### ISSUE TITLE
STM32_CORE_VERSION error

### ISSUE THREAD

**Issue by dungar43** [AndrewBCN/STM32-GPSDO#3]
I am new to this. After researching the error below I do'nt know what to do about it. 
#error "Due to API change, this sketch is compatible with STM32_CORE_VERSION  >= 0x02000000"
I am compiling your code on the Arduino IDE 1.8.19 on a clone Blackpill. Libraries all work except for this error.

**Comment by AndrewBCN** [comment]
This error during compilation means **you should update** the STM32 Arduino Core to a version 2.0.0 or later. The latest version is 2.2.0 and you can find it here: https://github.com/stm32duino/Arduino_Core_STM32.
This is very easy to do and takes just a couple of minutes. You are probably using one of the older versions (1.9.0 or earlier) which have bugs that prevent proper compilation of the STM32 GPSDO code.

**Comment by dungar43** [comment]
Thanks for the prompt reply. I'm getting back to this now and I can compile
and load the code on to the F411 but I can't get past the GPS
initialization.  Looks like you use Serial1
for GPS communication but I can't see what IO pins are assigned to Serial1.
I'm loading the code using a UART on pins A9,10.  I find how to use serial
ports on the  STM32 series to be confusing. Any ideas will be  appreciated.

**Comment by felixd** [comment]
Hi, If I can jump into this thread. 

@dungar43 **A9 and A10** pins are used for UART communication with GPS.

You can find Andrews **Schematics** here
https://www.eevblog.com/forum/projects/yet-another-diy-gpsdo-yes-another-one/msg3821813/#msg3821813

**Comment by dungar43** [comment]
Great that's a big help. Thanks
