### ISSUE TITLE
Circuit diagram request

### ISSUE THREAD

**Issue by instantcrow** [AndrewBCN/STM32-GPSDO#7]
Love the project. Building it on a different STM32. Trying to decipher a circuit diagram from the code using different pins. Probably won't be using the optional sensors. Should you have a circuit diagram, might you kindly post it? Thanks. Using this for homebrew radio projects.

**Comment by AndrewBCN** [comment]
Thank you. The circuit diagram is available on the EEVBlog forum, in this thread: https://www.eevblog.com/forum/projects/yet-another-diy-gpsdo-yes-another-one/
And in that thread you can find a lot more information on this project.
